services:
  - type: web
    name: dessa
    env: docker
    branch: main
    repo: https://github.com/Adarshdeav/Dessa.git
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
